version: "3.8"

services:
  wordpress:
    image: grueneschweiz/raisenow-community:latest
    build:
      context: .
      dockerfile: "./.docker/wordpress.Dockerfile"
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DEBUG: 1
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - "mysql"
    volumes:
      - ".:/var/www/html/wp-content/plugins/raisenow-community"
      - "./.docker/addon-php.ini:/usr/local/etc/php/conf.d/addon-php.ini:ro"
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db: